version: '3'
services:
  my_flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test
    ports:
      - "5433:5433"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge