version: '3'
services:
  my_flask_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "5000"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test
      DB_HOST: db
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test
    ports:
      - "5433:5433"