"""empty message

Revision ID: c98fba6595db
Revises: a5eaf54ac574
Create Date: 2024-12-16 23:37:22.556403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98fba6595db'
down_revision = 'a5eaf54ac574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

        batch_op.drop_column('type')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=10), nullable=False))
        batch_op.create_foreign_key('fk_category_user_id', 'user', ['user_id'], ['id'])  # Вказати ім'я обмеження
        batch_op.drop_column('description')

    # ### end Alembic commands ###
